name: Form Validation

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Choose the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Authenticate with Vercel
      run: npx vercel login --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Pass the Vercel token as an environment variable

    - name: Build and deploy to Vercel
      run: |
        # Build your project (replace with your build command)
        npm run build

        # Deploy to Vercel
        npx vercel --prod
